//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBContext.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [MiCarDrive]
        ///
        ///INSERT INTO [dbo].[EVENT_TYPES] ([EVENT_TYPE_ID],[NAME]) VALUES (&apos;72F112E7-B4A5-4AD6-9C48-8218C71F360D&apos;,&apos;Service&apos;),
        ///																(&apos;DD8C7244-FF3C-42D5-80BC-6736ACE9B875&apos;,&apos;Washing&apos;),
        ///																(&apos;96A157C5-E6C3-44AF-8D35-C6C4CC66F499&apos;,&apos;Refill&apos;),
        ///																(&apos;EC63DE58-04EA-4447-A40A-6170407C844C&apos;,&apos;Other&apos;)
        ///GO
        ///
        ///INSERT INTO [dbo].[FUEL_TYPES] ([FUEL_TYPE_ID],[NAME]) VALUES (&apos;5A3F7333-0247-4114-A853-28B2C294AA14&apos;,&apos;Diezel&apos;),
        ///															  (&apos;FAE003E6-AA22-42C0-9863-781FA53B5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertInitialData {
            get {
                return ResourceManager.GetString("InsertInitialData", resourceCulture);
            }
        }
    }
}
